require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

prepare_react_native_project!

platform :ios, '13.0'

target 'RNTextInputMask' do
  use_frameworks!
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])

  pod 'InputMask'
end
